export const projects = [
  {
    title: 'Pinghome',
    description:"",
    image: '/images/8.png',
    tags: ['React', 'JavaScript'],
    source: '',
    visit: 'https://www.pinghome.io/',
    id: 1,
  },
  {
    title: 'Kloogtech',
    description:"",
    image: '/images/9.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/kloogtech',
    visit: 'https://www.kloogtech.com/',
    id: 2,
  },
  {
    title: 'Metaversus',
    description:"",
    image: '/images/10.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Amina2000-a/Metaverse',
    visit: 'https://metaverse-ten-flax.vercel.app/',
    id: 3,
  },
  {
    title: 'Restaurant App',
    description:"",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Amina2000-a/RestaurantApp',
    visit: 'https://restaurant-project-akrmv.netlify.app/',
    id: 4,
  },
  {
    title: 'GPT-3 App',
    description: "",
    image: '/images/3.png',
    tags: ['React', 'JavaScript', 'WebRTC'],
    source: 'https://github.com/Amina2000-a/Gpt-3',
    visit: 'https://gpt3-webproject.netlify.app/',
    id: 5,
  },
  {
    title: 'Bank App',
    description:"",
    image: '/images/6.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Amina2000-a/RestaurantApp',
    visit: 'https://fullresponsive-bank-app.netlify.app',
    id: 6,
  },
  {
    title: '3d Portfolio',
    description: "",
      image: '/images/5.png',
      tags: ['React', 'JavaScript', 'Three.js'],
    source: 'https://github.com/Amina2000-a/Gpt-3',
    visit: 'https://amina-northwind.netlify.app/',
    id: 7,
  },
    {
    title: 'Roofs',
    description: "",
      image: '/images/7.png',
      tags: ['React', 'JavaScript'],
    source: '',
    visit: 'https://roofs.az/',
    id: 8,
  },
  {
    title: 'AI Image Creator',
    description: "",
    image: '/images/1.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/Amina2000-a/OpenAI',
    visit: 'https://northwind.website/',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'After being admitted to the Computer Engineering major of the Information Technologies and Management faculty of Azerbaijan State Oil and Industry University, I started programming.', },
  { year: 2018, text: 'I took a programming course at Compar Academy, and after finishing the course, I did an internship there as a mentor for a year.', },
  { year: 2019, text: 'I started working as a graphic and UX/UI designer at Maffin Agency.', },
  { year: 2020, text: 'I started working as a UX/UI designer and Front-end developer at Flex Agency.', },
  { year: 2021, text: 'I was admitted to the Computer Science (SABAH) major of the Faculty of Applied Mathematics and Cybernetics of Baku State University and was awarded a master`s degree with honors in 2023.', },
  { year: 2023, text: 'I worked as a front-end developer at Pinghome', }
];