export const projects = [
  {
    title: 'Pinghome',
    description:"",
    image: '/images/8.png',
    tags: ['React', 'JavaScript'],
    source: '',
    visit: 'https://www.pinghome.io/',
    id: 1,
  },
  {
    title: 'Kloogtech',
    description:"",
    image: '/images/9.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/kloogtech',
    visit: 'https://www.kloogtech.com/',
    id: 2,
  },
  {
    title: 'Metaversus',
    description:"",
    image: '/images/10.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Amina2000-a/Metaverse',
    visit: 'https://metaverse-ten-flax.vercel.app/',
    id: 3,
  },
  {
    title: 'Restaurant App',
    description:"",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Amina2000-a/RestaurantApp',
    visit: 'https://restaurant-project-akrmv.netlify.app/',
    id: 4,
  },
  {
    title: 'GPT-3 App',
    description: "",
    image: '/images/3.png',
    tags: ['React', 'JavaScript', 'WebRTC'],
    source: 'https://github.com/Amina2000-a/Gpt-3',
    visit: 'https://gpt3-webproject.netlify.app/',
    id: 5,
  },
  {
    title: 'Bank App',
    description:"",
    image: '/images/6.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Amina2000-a/RestaurantApp',
    visit: 'https://fullresponsive-bank-app.netlify.app',
    id: 6,
  },
  {
    title: '3d Portfolio',
    description: "",
      image: '/images/5.png',
      tags: ['React', 'JavaScript', 'Three.js'],
    source: 'https://github.com/Amina2000-a/Gpt-3',
    visit: 'https://amina-northwind.netlify.app/',
    id: 7,
  },
    {
    title: 'Roofs',
    description: "",
      image: '/images/7.png',
      tags: ['React', 'JavaScript'],
    source: '',
    visit: 'https://roofs.az/',
    id: 8,
  },
  {
    title: 'AI Image Creator',
    description: "",
    image: '/images/1.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/Amina2000-a/OpenAI',
    visit: 'https://northwind.website/',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Azərbaycan Dövlət Neft və Sənaye Universitetinin İnformasiya Texnologiyaları və İdarəetmə fakültəsinin Kompüter Mühəndisliyi ixtisasına qəbul olduqdan sonra proqramlaşdırma ilə məşğul olmağa başladım.', },
  { year: 2018, text: 'Compar Academy - də proqramlaşdırma kursu keçdim və kursu bitirdikdən sonra bir il orada mentor kimi təcrübə keçdim.', },
  { year: 2019, text: 'Maffin Agency - də qrafik və UX/UI dizayner kimi çalışmağa başladım.', },
  { year: 2020, text: 'Flex Agency - də UX/UI dizayner və Front-end developer kimi fəaliyyətə başladım.', },
  { year: 2021, text: 'Bakı Dövlət Universitetinin Tətbiqi Riyaziyyat və Kibernetika fakültəsinin Kompüter Elmləri (SABAH) ixtisasına qəbul oldum və 2023-cü ildə fərqlənmə ilə magistr dərəcəsinə layiq görüldüm.', },
  { year: 2023, text: 'Pinghome-da front-end developer kimi işə başladım.', }
];